record_topics:
  - /can/pedal/clutch
  - /can/steer/clutch
  - /localization/kinematic_state
  - /diagnostics
  # Mobileye デバッグ用？
  - /sensing/camera/mobileye/can_rx
  - /sensing/camera/mobileye/can_tx
  - /perception/object_recognition/mobileye/detected_objects
  # Centerpoint デバッグ用？
  - /perception/object_recognition/detection/centerpoint/objects
  - /perception/object_recognition/detection/centerpoint/validation/objects
  - /perception/object_recognition/detection/clustering_centerpoint_merged_objects
  # ペダルキャリブレーションに必要なtopic
  - /control/command/actuation_cmd
  - /vehicle/status/steering_status
  - /vehicle/status/velocity_status
  - /vehicle/status/gear_status
  - /tf
  - /tf_static
  - /can/can100
  - /can/pedal/can_receive
  - /sensing/vcan/vcan_accel_pedal_status_aw
  - /sensing/vcan/can_tx
control_topic: /autoware/state
memo_topic: /record_memo_text
interval_sec: 60  # 秒
bag_output_dir: /home/sit/rosbag_recorder/  # ベースディレクトリ
